title: QADAO
description: "Decentralised Assurance of Quality"
logo: /assets/images/qadao.jpg
theme: jekyll-theme-minimal
show_downloads: false

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:slug/

# Exclude directories from Jekyll processing
exclude:
  - specs/
  - vendor/
  - README.md
  - TEST_BLOG.md
  - test-blog.sh

# Social Media
x_handle: https://x.com/qa_dao
youtube_handle: https://youtube.com/@qadao

# SEO
author: Stephen Whitenstall
keywords: Quality Assurance, DAO, Blockchain, Cardano, SingularityNET, Open Source, Decentralized, Community Building
